# Generated by Django 5.0.6 on 2024-05-23 17:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default=' inactive', max_length=15, verbose_name='status')),
                ('name', models.CharField(db_index=True, default='Anonymous', max_length=200, verbose_name='name')),
                ('message', models.CharField(db_index=True, default='Anonymous', max_length=200, verbose_name='message')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
