# Generated by Django 5.0.6 on 2024-06-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='STATUS',
        ),
        migrations.RemoveField(
            model_name='item',
            name='message',
        ),
    ]
